$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: inference-feature-selection-train
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file: conda-train.yml